const ClassListActionsConstants = {
  LOAD_CLASSES: "LOAD_CLASSES",
  LOAD_CLASSES_SUCCESS: "LOAD_CLASSES_SUCCESS",
  LOAD_CLASSES_FAILURE: "LOAD_CLASSES_FAILURE",
  JOIN_CLASS: "JOIN_CLASS",
  JOIN_CLASS_SUCC: "JOIN_CLASS_SUCC",
  JOIN_CLASS_FAIL: "JOIN_CLASS_FAIL",
  JOIN_WAITING: "JOIN_WAITING",
  JOIN_WAITING_SUCC: "JOIN_WAITING_SUCC",
  JOIN_WAITING_FAIL: "JOIN_WAITING_FAIL",
};

export { ClassListActionsConstants };
